---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aws-cli-blocked
spec:
  podSelector:
    matchLabels:
      app: aws-cli-blocked
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: secure-api
    - podSelector:
        matchLabels:
          k8s-app: secure-api